language: ruby

os: osx

install:
  # Slow but needed (see https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos).
  - brew update
  - brew config
  - brew --env

script:
  - ALL="./Formula/*.rb"
  - brew audit --strict ${ALL}
  - brew install --verbose ${ALL}
  - brew test --verbose ${ALL}
